name: Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: "logicer16/workflows/.github/workflows/docker.yml@main"
    permissions:
      contents: read
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    
  dockerhub-description:
    uses: "logicer16/workflows/.github/workflows/dockerhub-description.yml@main"
    needs:
      - publish
    permissions:
      contents: read
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
