name: Update Repo 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-repo:
    uses: logicer16/workflows/.github/workflows/update-repo.yml@main
    with:
      upstream: AleixoLucas42/duplicati-prometheus-exporter
    
  update-docker-image:
    uses: ./.github/workflows/docker.yml
    needs: update-repo
    if: ${{ needs.update-repo.outputs.new-commits == 'true' }}
    secrets: inherit
